config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :logins
  resources :klasses
  resources :reviews
  resources :users
  resources :tutors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/login.rb
class Login < ApplicationRecord
  has_one :tutor
  has_one :user

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: %i[ show edit update destroy ]

  # GET /logins or /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1 or /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins or /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to login_url(@login), notice: "Login was successfully created." }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1 or /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to login_url(@login), notice: "Login was successfully updated." }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1 or /logins/1.json
  def destroy
    @login.destroy

    respond_to do |format|
      format.html { redirect_to logins_url, notice: "Login was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def login_params
      params.require(:login).permit(:username, :user_type, :password, :password_confirmation)
    end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/_form.html.erb
<%= form_with(model: login) do |form| %>
  <% if login.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
        <% login.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :user_type, style: "display: block" %>
    <%= form.text_field :user_type %>
  </div>

  <div class="field">
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password, id: :login_password %>
  </div>
  <div class="field">
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation, id: :login_password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/logins/_login.html.erb
<div id="<%= dom_id login %>">
  <p>
    <strong>Username:</strong>
    <%= login.username %>
  </p>

  <p>
    <strong>User type:</strong>
    <%= login.user_type %>
  </p>

</div>

app/views/logins/edit.html.erb
<h1>Editing login</h1>

<%= render "form", login: @login %>

<br>

<div>
  <%= link_to "Show this login", @login %> |
  <%= link_to "Back to logins", logins_path %>
</div>

app/views/logins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Logins</h1>

<div id="logins">
  <% @logins.each do |login| %>
    <%= render login %>
    <p>
      <%= link_to "Show this login", login %>
    </p>
  <% end %>
</div>

<%= link_to "New login", new_login_path %>

app/views/logins/new.html.erb
<h1>New login</h1>

<%= render "form", login: @login %>

<br>

<div>
  <%= link_to "Back to logins", logins_path %>
</div>

app/views/logins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @login %>

<div>
  <%= link_to "Edit this login", edit_login_path(@login) %> |
  <%= link_to "Back to logins", logins_path %>

  <%= button_to "Destroy this login", @login, method: :delete %>
</div>