config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :logins
  resources :klasses
  resources :reviews
  resources :users
  resources :tutors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/tutor.rb
class Tutor < ApplicationRecord
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  before_action :set_tutor, only: %i[ show edit update destroy ]

  # GET /tutors or /tutors.json
  def index
    @tutors = Tutor.all
  end

  # GET /tutors/1 or /tutors/1.json
  def show
  end

  # GET /tutors/new
  def new
    @tutor = Tutor.new
  end

  # GET /tutors/1/edit
  def edit
  end

  # POST /tutors or /tutors.json
  def create
    @tutor = Tutor.new(tutor_params)

    respond_to do |format|
      if @tutor.save
        format.html { redirect_to tutor_url(@tutor), notice: "Tutor was successfully created." }
        format.json { render :show, status: :created, location: @tutor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1 or /tutors/1.json
  def update
    respond_to do |format|
      if @tutor.update(tutor_params)
        format.html { redirect_to tutor_url(@tutor), notice: "Tutor was successfully updated." }
        format.json { render :show, status: :ok, location: @tutor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1 or /tutors/1.json
  def destroy
    @tutor.destroy

    respond_to do |format|
      format.html { redirect_to tutors_url, notice: "Tutor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor
      @tutor = Tutor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tutor_params
      params.require(:tutor).permit(:start_date, :subject, :location, :description, :degree, :email, :phone_number, :login_id)
    end
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/tutors/_form.html.erb
<%= form_with(model: tutor) do |form| %>
  <% if tutor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tutor.errors.count, "error") %> prohibited this tutor from being saved:</h2>

      <ul>
        <% tutor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.number_field :id %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :subject, style: "display: block" %>
    <%= form.text_field :subject %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :degree, style: "display: block" %>
    <%= form.text_field :degree %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :login_id, style: "display: block" %>
    <%= form.number_field :login_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tutors/_tutor.html.erb
<div id="<%= dom_id tutor %>">
  <p>
    <strong>Id:</strong>
    <%= tutor.id %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= tutor.start_date %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= tutor.subject %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= tutor.location %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= tutor.description %>
  </p>

  <p>
    <strong>Degree:</strong>
    <%= tutor.degree %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= tutor.email %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= tutor.phone_number %>
  </p>

  <p>
    <strong>Login:</strong>
    <%= tutor.login_id %>
  </p>

</div>

app/views/tutors/edit.html.erb
<h1>Editing tutor</h1>

<%= render "form", tutor: @tutor %>

<br>

<div>
  <%= link_to "Show this tutor", @tutor %> |
  <%= link_to "Back to tutors", tutors_path %>
</div>

app/views/tutors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tutors</h1>

<div id="tutors">
  <% @tutors.each do |tutor| %>
    <%= render tutor %>
    <p>
      <%= link_to "Show this tutor", tutor %>
    </p>
  <% end %>
</div>

<%= link_to "New tutor", new_tutor_path %>

app/views/tutors/new.html.erb
<h1>New tutor</h1>

<%= render "form", tutor: @tutor %>

<br>

<div>
  <%= link_to "Back to tutors", tutors_path %>
</div>

app/views/tutors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tutor %>

<div>
  <%= link_to "Edit this tutor", edit_tutor_path(@tutor) %> |
  <%= link_to "Back to tutors", tutors_path %>

  <%= button_to "Destroy this tutor", @tutor, method: :delete %>
</div>