config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :logins
  resources :klasses
  resources :reviews
  resources :users
  resources :tutors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController
  before_action :set_klass, only: %i[ show edit update destroy ]

  # GET /klasses or /klasses.json
  def index
    @klasses = Klass.all
  end

  # GET /klasses/1 or /klasses/1.json
  def show
  end

  # GET /klasses/new
  def new
    @klass = Klass.new
  end

  # GET /klasses/1/edit
  def edit
  end

  # POST /klasses or /klasses.json
  def create
    @klass = Klass.new(klass_params)

    respond_to do |format|
      if @klass.save
        format.html { redirect_to klass_url(@klass), notice: "Klass was successfully created." }
        format.json { render :show, status: :created, location: @klass }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @klass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /klasses/1 or /klasses/1.json
  def update
    respond_to do |format|
      if @klass.update(klass_params)
        format.html { redirect_to klass_url(@klass), notice: "Klass was successfully updated." }
        format.json { render :show, status: :ok, location: @klass }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @klass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /klasses/1 or /klasses/1.json
  def destroy
    @klass.destroy

    respond_to do |format|
      format.html { redirect_to klasses_url, notice: "Klass was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_klass
      @klass = Klass.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def klass_params
      params.require(:klass).permit(:klass_date, :subject, :subject_level, :status, :tutor_id, :user_id)
    end
end

app/helpers/klasses_helper.rb
module KlassesHelper
end

app/views/klasses/_form.html.erb
<%= form_with(model: klass) do |form| %>
  <% if klass.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(klass.errors.count, "error") %> prohibited this klass from being saved:</h2>

      <ul>
        <% klass.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :klass_date, style: "display: block" %>
    <%= form.date_field :klass_date %>
  </div>

  <div>
    <%= form.label :subject, style: "display: block" %>
    <%= form.text_field :subject %>
  </div>

  <div>
    <%= form.label :subject_level, style: "display: block" %>
    <%= form.text_field :subject_level %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :tutor_id, style: "display: block" %>
    <%= form.number_field :tutor_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/klasses/_klass.html.erb
<div id="<%= dom_id klass %>">
  <p>
    <strong>Klass date:</strong>
    <%= klass.klass_date %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= klass.subject %>
  </p>

  <p>
    <strong>Subject level:</strong>
    <%= klass.subject_level %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= klass.status %>
  </p>

  <p>
    <strong>Tutor:</strong>
    <%= klass.tutor_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= klass.user_id %>
  </p>

</div>

app/views/klasses/edit.html.erb
<h1>Editing klass</h1>

<%= render "form", klass: @klass %>

<br>

<div>
  <%= link_to "Show this klass", @klass %> |
  <%= link_to "Back to klasses", klasses_path %>
</div>

app/views/klasses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Klasses</h1>

<div id="klasses">
  <% @klasses.each do |klass| %>
    <%= render klass %>
    <p>
      <%= link_to "Show this klass", klass %>
    </p>
  <% end %>
</div>

<%= link_to "New klass", new_klass_path %>

app/views/klasses/new.html.erb
<h1>New klass</h1>

<%= render "form", klass: @klass %>

<br>

<div>
  <%= link_to "Back to klasses", klasses_path %>
</div>

app/views/klasses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @klass %>

<div>
  <%= link_to "Edit this klass", edit_klass_path(@klass) %> |
  <%= link_to "Back to klasses", klasses_path %>

  <%= button_to "Destroy this klass", @klass, method: :delete %>
</div>